- name: "Maak een folder met de naam 'NginxPHP/nginx' aan"
  file:
    path: "{{ homedir }}/NginxPHP/nginx"
    state: directory
    mode: 0755

- name: "Kopieer de docker-compose naar de target"
  copy:
    src: docker-compose.yml
    dest: "{{ homedir }}/NginxPHP"
    owner: "{{ ansible_user }}"
    group: "docker"
    mode: 0755    

- name: "kopieer het bestand 'default.conf' & 'Dockerfile' naar de folder 'NginxPHP/nginx'"
  copy:
    src: "{{ item }}"
    dest: "{{ homedir }}/NginxPHP/nginx"
  loop:
    - default.conf
    - Dockerfile

- name: "Kopieer de website naar 'NginxPHP/data'"
  copy:
    src: website/
    dest: "{{ homedir }}/NginxPHP/data"

- name: "Start de 'mysql & phpmyadmin' containers"
  docker_container:
    name: "{{ item }}"
    state: started
  loop:
    - nginxphp_nginx_1
    - nginxphp_php_1