- name: Update + upgrade the system
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: dist

- name: Install system packages
  apt:
    name: "{{ system_packages }}"
    state: latest
