- name: Ensure sql files have a place to be stored
  file:
    path: "{{ homedir }}/SQL"
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    mode: "0750"
    state: directory

- name: Copy the table script to the remote server
  copy:
    src: scripts/diet-table.sql
    dest: "{{ homedir }}/SQL/diet-table.sql"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0750"

- name: Copy SQL script to MySQL container
  command: docker cp {{ homedir }}/SQL/diet-table.sql db:/tmp/diet_script.sql

# - name: Execute SQL script
#   command: docker exec db sh -c "exec mysql -u joshua kerntaak < /tmp/diet_script.sql"
