- name: "Maak een folder met de naam 'SQL' aan"
  file:
    path: "{{ homedir }}/SQL"
    group: "{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    mode: "0750"
    state: directory

- name: "Kopieer de export naar de target"
  copy:
    src: scripts/init.sql
    dest: "{{ homedir }}/SQL/init.sql"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0750"

- name: "Kopieer de export naar de target database"
  command: docker cp {{ homedir }}/SQL/init.sql db:/tmp/diet_script.sql

- name: "Voer de export uit op de target database"
  command: docker exec db sh -c "exec mysql -u{{ ansible_user }} -p{{ mysql.mysql_user_password }} Kerntaak < /tmp/diet_script.sql"
