- name: Ensure docker group exists
  group:
    name: docker
    state: present

- name: Ensure the user is in the sudo and docker group
  user:
    name: "{{ ansible_user }}"
    groups: sudo,docker
    append: true

- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - docker.io
    - docker-compose
    - python3-pip

- name: Ensure the docker service is enabled and running
  service:
    name: docker
    state: started
    enabled: true

- name: Pull the 2 images
  docker_image:
    name: "{{ item }}"
    state: present
    source: pull
  loop:
    - mysql:5.7
    - phpmyadmin/phpmyadmin:latest

- name: Build up the mysql container
  docker_container:
    name: db
    image: mysql:5.7
    state: present
    restart: true
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql.mysql_root_password }}"
      MYSQL_USER: "{{ mysql.mysql_user }}"
      MYSQL_PASSWORD: "{{ mysql.mysql_user_password }}"
      MYSQL_DATABASE: "{{ mysql.mysql_database }}"
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    restart_policy: always
    
- name: Build up the phpmyadmin container
  docker_container:
    name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    state: present
    env:
      PMA_HOST: db
      PMA_PORT: "3306"
      PMA_ARBITRARY: "1"
    restart: true
    ports:
      - "8080:80"
    restart_policy: always

- name: Start the docker containers
  shell:
    cmd: docker start db phpmyadmin